<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find my_robot_description)/urdf/common_properties.xacro"/>
<xacro:include filename="$(find my_robot_description)/urdf/mobile_base.xacro"/>
<xacro:include filename="$(find my_robot_description)/urdf/camera.xacro"/>
<xacro:include filename="$(find my_robot_description)/urdf/mobile_arm.xacro"/>
<!-- <xacro:include filename="$(find my_robot_description)/urdf/mobile_base_gazebo.xacro"/> -->
<!-- <xacro:include filename="$(find my_robot_description)/urdf/arm_gazebo.xacro"/> -->
<xacro:include filename="$(find my_robot_description)/urdf/my_controllers.urdf.xacro"/>

<joint name = "arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link = "arm_base_footprint"/>
    <origin xyz="${base_length/2 - arm_base_length/2} 0 ${base_height+arm_base_height/2}" rpy="0 0 0"/>
</joint>

</robot>