<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
   
    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.02"/>
    <xacro:property name="forearm_link_radius" value="0.02"/>
    <xacro:property name="forearm_link_length" value="0.3"/>
    <xacro:property name="hand_link_radius" value="0.02"/>
    <xacro:property name="hand_link_length" value="0.3"/>

        <link name="arm_base_footprint"/>
        <joint name = "base_footprint_arm_joint" type="fixed">
            <parent link="arm_base_footprint"/>
            <child link = "arm_base_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <link name="arm_base_link">
            <visual>
                <geometry>
                    <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="orange"/> 
            </visual>
            <collision>
                <geometry>
                    <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:box_inertia  m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}"
                                xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </link>

        <joint name = "base_forarm_joint" type="revolute">
            <parent link="arm_base_link"/>
            <child link = "forearm_link"/>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.1" friction="0.1"/>
            <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        </joint>

        <link name="forearm_link">
            <visual>
                <geometry>
                    <cylinder radius="${forearm_link_radius}" length="${forearm_link_length}" />
                </geometry>
                <origin xyz="0 0 ${forearm_link_length/2.0}" rpy="0 0 0" />
                <material name="yellow"/> 
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${forearm_link_radius}" length="${forearm_link_length}" />
                </geometry>
                <origin xyz="0 0 ${forearm_link_length/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:wheel_inertia  m="0.3" r="${forearm_link_radius}" l="${forearm_link_length}"
                                    xyz="0 0 ${forearm_link_length/2.0}" rpy="0 0 0"/>
        </link>

        <link name="hand_link">
            <visual>
                <geometry>
                    <cylinder radius="${hand_link_radius}" length="${hand_link_length}" />
                </geometry>
                <origin xyz="0 0 ${hand_link_length/2.0}" rpy="0 0 0" />
                <material name="orange"/> 
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${hand_link_radius}" length="${hand_link_length}" />
                </geometry>
                <origin xyz="0 0 ${hand_link_length/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:wheel_inertia  m="0.3" r="${hand_link_radius}" l="${hand_link_length}"
                                    xyz="0 0 ${hand_link_length/2.0}" rpy="0 0 0"/>
        </link>

        <joint name = "forearm_hand_joint" type="revolute">
            <parent link="forearm_link"/>
            <child link = "hand_link"/>
            <origin xyz="0 0 ${hand_link_length}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.1" friction="0.1"/>
            <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        </joint>
</robot>