controller_manager:
  ros__parameters:
    update_rate: 10000
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    arm_cont:
      type: robot_arm_controller/RobotArmController

diff_cont:
  ros__parameters:  
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    wheel_separation: 0.40
    wheel_radius: 0.1

    use_stamped_vel: true 

arm_cont:
  ros__parameters:
    joints:
        - base_forarm_joint
        - forearm_hand_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity


